env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - next/core-web-vitals
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.eslint.json
rules:
  prefer-template: off
  no-shadow: off
  import/extensions: off
  import/prefer-default-export: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  class-methods-use-this: off
  max-classes-per-file: off
  no-underscore-dangle: off
  no-bitwise: off
  react/jsx-curly-brace-presence: off
  react/no-array-index-key: off
  react/require-default-props: off
  "@typescript-eslint/no-shadow": off
  "@typescript-eslint/lines-between-class-members": off
  "@typescript-eslint/no-unused-vars": off
settings:
  react:
    version: detect
