name: Build Test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        run: npm run build
        env:
          BASE_URL: ""
        shell: bash

      - name: Export
        run: npm run export
        shell: bash
