---
name: Build Test

on:
  pull_request:

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build
        with:
          base-url: "/"
