name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Build Packages
        run: npm run ci:packages && npm run build:packages
        shell: bash

      - name: Install Node Packages
        run: npm ci
        working-directory: website
        shell: bash

      - name: Build
        run: npm run build
        working-directory: website
        shell: bash

  build-learn:
    name: Build Learn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Build Packages
        run: npm run ci:packages && npm run build:packages
        shell: bash

      - name: Install Node Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Build
        run: npm run build
        working-directory: learn
        shell: bash
        env:
          BASE_URL: ""

      - name: Export
        run: npm run export
        working-directory: learn
        shell: bash

  build-translate:
    name: Build Translate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Build Packages
        run: npm run ci:packages && npm run build:packages
        shell: bash

      - name: Install Node Packages
        run: npm ci
        working-directory: translate
        shell: bash

      - name: Build
        run: npm run build
        working-directory: translate
        shell: bash

  build-braille-package:
    name: Build Braille Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm run ci:packages
        shell: bash

      - name: Build
        run: npm run build:packages
        shell: bash

  type-check-website:
    name: Type Check Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Build Packages
        run: npm run ci:packages && npm run build:packages
        shell: bash

      - name: Install Node Packages
        run: npm ci
        working-directory: website
        shell: bash

      - name: Type Check
        run: npm run type-check
        working-directory: website
        shell: bash

  type-check-learn:
    name: Type Check Learn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Build Packages
        run: npm run ci:packages && npm run build:packages
        shell: bash

      - name: Install Node Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Type Check
        run: npm run type-check
        working-directory: learn
        shell: bash

  type-check-translate:
    name: Type Check Translate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Build Packages
        run: npm run ci:packages && npm run build:packages
        shell: bash

      - name: Install Node Packages
        run: npm ci
        working-directory: translate
        shell: bash

      - name: Type Check
        run: npm run type-check
        working-directory: translate
        shell: bash

  type-check-braille-package:
    name: Type Check Braille Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: packages/braille
        shell: bash

      - name: Type Check
        run: npm run type-check
        working-directory: packages/braille
        shell: bash

  test-braille-package:
    name: Test Braille Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: packages/braille
        shell: bash

      - name: Test
        run: npm test
        working-directory: packages/braille
        shell: bash

  eslint-website:
    name: ESLint Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: website
        shell: bash

      - name: Run ESLint
        run: npm run lint:check
        working-directory: website

  eslint-learn:
    name: ESLint Learn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Run ESLint
        run: npx eslint --max-warnings 0 .
        working-directory: learn

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        shell: bash

      - name: Prettier
        run: npm run format:check
        shell: bash

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Python Packages
        run: pip install -r translate-backend/requirements.txt
        shell: bash

      - name: Black
        run: black --check .
        shell: bash
