name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-front:
    name: Build Front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: cd web && npm ci
        shell: bash

      - name: Build
        run: cd web && npm run build
        shell: bash
