name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Build
        run: npm run build
        working-directory: learn
        env:
          BASE_URL: ""
        shell: bash

      - name: Export
        run: npm run export
        working-directory: learn
        shell: bash

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Run ESLint
        run: npx eslint --max-warnings 0 .
        working-directory: learn

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        shell: bash

      - name: Prettier
        run: npx prettier --check .
        shell: bash

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Type Check
        run: npm run type-check
        working-directory: learn
        shell: bash
