name: Deploy to Cloudflare Pages

on:
  push:

concurrency:
  group: "cloudflare-pages"
  cancel-in-progress: false

jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Packages
        run: npm ci
        working-directory: website
        shell: bash

      - name: Build
        run: npm run build
        working-directory: website
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website/dist

  deploy-website:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: build-website
    steps:
      - name: Dowload Artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website/dist

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-tutor-website
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: website
          wranglerVersion: "3"

  build-learn:
    name: Build Learn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Packages
        run: npm ci
        working-directory: learn
        shell: bash

      - name: Build
        run: npm run build
        working-directory: learn
        shell: bash

      - name: Export
        run: npm run export
        working-directory: learn
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: learn
          path: learn/out

  deploy-learn:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: build-learn
    steps:
      - name: Dowload Artifact
        uses: actions/download-artifact@v4
        with:
          name: learn
          path: learn/out

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-tutor-learn
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: learn
          wranglerVersion: "3"
