name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        shell: bash

      - name: Make BASE_URL
        uses: actions/github-script@v6
        id: base-url
        with:
          script: |
            const githubRepositoryName = "${{ github.event.repository.name }}"; // repo
            const prNumber = "${{ github.event.number }}"; // pr-number
            const baseUrl = `${repositoryBaseUrl}/pr-preview/pr-${prNumber}`;
            return baseUrl; // /<repo>/pr-preview/pr-<pr-number>
          result-encoding: string

      - name: Build
        run: npm run build
        env:
          BASE_URL: ${{ steps.base-url.outputs.result }}
        shell: bash

      - name: Export
        run: npm run export
        shell: bash

      - name: Add nojekill
        run: touch out/.nojekyll
        shell: bash

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: out
